return {
	root={
		border_width_bottom=1,
		border_width_left=1,
		border_width_right=1,
		border_width_top=1,
		h=431.5,
		layout_type=1,
		min_ch=431.5,
		min_cw=304,
		span_count=2,
		text_align_x=4,
		text_cursor_count=1,
		text_cursors={
			{
				text_cursor_offset=25,
				text_cursor_sel_offset=25,
				text_cursor_x=79
			}
		},
		text_spans={
			{
				span_font_id=0,
				span_font_size=25
			},
			{
				span_font_id=0,
				span_font_size=35,
				span_offset=10
			}
		},
		text_utf8='LuaJIT\'s ffi is the best!',
		w=304,
		x=85,
		y=78.5
	},
	selected_layer_path={
	},
	tab='Background'
}