return {
	root={
		background_color=4294967295,
		background_type=1,
		border_width_bottom=1,
		border_width_left=1,
		border_width_right=1,
		border_width_top=1,
		h=837.5,
		layout_type=1,
		min_ch=784.5,
		min_cw=741.5,
		padding_bottom=26.5,
		padding_left=26.5,
		padding_right=26.5,
		padding_top=26.5,
		span_count=4,
		text_align_x=1,
		text_align_y=2,
		text_cursor_count=1,
		text_cursors={
			{
				text_cursor_offset=167,
				text_cursor_sel_offset=57,
				text_cursor_x=99.5
			}
		},
		text_spans={
			{
				span_font='SourceHanSans.ttc',
				span_font_face_index=38,
				span_font_size=37,
				span_lang='en-us',
				span_text_color=255
			},
			{
				span_font='SourceHanSans.ttc',
				span_font_face_index=6,
				span_font_size=15,
				span_lang='en-us',
				span_offset=5,
				span_text_color=255
			},
			{
				span_font='SourceHanSans.ttc',
				span_font_face_index=15,
				span_font_size=19,
				span_lang='en-us',
				span_offset=28,
				span_text_color=4279835135
			},
			{
				span_font='SourceHanSans.ttc',
				span_font_face_index=6,
				span_font_size=15,
				span_lang='en-us',
				span_offset=35,
				span_text_color=255
			}
		},
		text_utf8='TODO:\r- test bidi text with subsegs.\r- test lang and script tagging.\r- implement layer margins.\r- jit.off layer:draw() because of custom-draw callbacks\r- span-at-cursor.\r- implements embeds.\r- implement tab-stops.\r- implement underline and strike-through (simple version).\r- test color fonts and emoji scaling.\r\r\n',
		w=794.5,
		x=61,
		y=39
	},
	selected_layer_path={
	},
	tab='Text'
}