return {
	root={
		border_width_bottom=1,
		border_width_left=1,
		border_width_right=1,
		border_width_top=1,
		h=400,
		layout_type=1,
		min_cw=328,
		span_count=1,
		text_cursor_count=1,
		text_cursors={
			{
				text_cursor_offset=1,
				text_cursor_sel_offset=2,
				text_cursor_x=109
			}
		},
		text_spans={
			{
				span_font='SourceHanSans.ttc',
				span_font_face_index=15,
				span_font_size=100
			}
		},
		text_utf8='a\244\128\128\128b',
		w=518,
		x=100,
		y=100
	},
	selected_layer_path={
	},
	tab='Layout'
}